# https://www.cs.colby.edu/maxwell/courses/tutorials/maketutor/
# https://www.learncpp.com

# In progress

COMPILER 		= g++
COMPILERFLAGS 	= -ggdb -pedantic-errors -Wall -Weffc++ -Wextra -Wconversion \
				  -Wsign-conversion -Werror -std=c++20

DEPENDENCIES 	= concurrency.h 
LIBRARIES		= 
OBJECTDIR 		= obj